### ISSUE TITLE
Ошибка в журнале при создании блога

### ISSUE THREAD

**Issue by yuri25** [sersar/altocms#1]
При создании блога в журнале пишет такую хрень 
`SQL Error: Column 'blog_count_vote' cannot be null at /...../myrita.ru/common/classes/modules/blog/mapper/Blog.mapper.class.php line 113
UPDATE rita_blog SET blog_title = 'Басики', blog_description = 'Рисунки и фото басиков', blog_type = 'open', blog_date_edit = '2019-03-11 22:09:45', blog_rating = 0, blog_count_vote = NULL, blog_count_user = NULL, blog_count_topic = NULL, blog_limit_rating_topic = 0 , blog_url = 'basiks_pict', blog_avatar = 'http://myrita.ru/uploads/images/00/00/02/2019/03/11/0u41889760-77528f4c-b71cf3c0.jpg' WHERE blog_id = 19`

Похожую проблему описывал тут https://github.com/altocms/altocms/issues/850
Но там как обычно разработчикам все похую... Где то еще читал, сейчас не могу найти к сожалению что типа виновата версия php или mysql что типа жестко проверяется на not null.... ХЗ как что пофиксить.... Там я помню костылем решил одно, но полезли другие жаловаться что не может быть null

**Comment by sersar** [comment]
Исправлено
